import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  useEffect(() => {
    Data();
  }, []);
  const Data = async () => {
    await axios
      .get("https://api.binance.com/api/v3/ticker/24hr")
      .then(async (res) => {
        const a = await res.data.filter((PriceInfo: any) => {
          if (PriceInfo.firstId !== -1) {
            return PriceInfo.symbol.substring(0, 3) === "ETH";
          }
        });
        console.log(a);
      })
      .catch((error) => {
        console.log(error);
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js!</h1>
      </main>
    </div>
  );
};

export default Home;
