import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";
import CardPrice from "../components/Home/CardPrice/CardPrice";
import { CoinsInfo } from "../interface/I-coins";
import styles from "../styles/Home.module.scss";
import { useSelector } from "react-redux";

import PageCounters from "../components/Home/PageCounter/PageCounters";
import { initialState } from "../redux/store";
import Search from "../components/Home/Search/Search";
import H_Header from "../components/Home/H_Header/H_Header";

const Home: NextPage = () => {
  const [countRenderCoin, setCountRenderCoin] = useState(1);
  const coinsInfo: Array<CoinsInfo> = useSelector(
    (state: initialState) => state.Coins.coinsInfo
  );
  const search = useSelector((state: initialState) => state.Coins.searchValue);

  const handelCountRenderCoin = (page: number) => [setCountRenderCoin(page)];

  useEffect(() => {
    if (search.active) {
      setCountRenderCoin(1);
    }
  }, [search.active]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {coinsInfo.length > 0 ? (
          <>
            <div>
              <h2>Markets</h2>
            </div>
            <div>
              <H_Header coins={coinsInfo} />
            </div>
            <div>
              <Search />
            </div>
            <div>
              <div>
                <div className={styles.cardsPrice}>
                  <CardPrice
                    //@ts-ignore
                    coins={search.active ? search.filter : coinsInfo}
                    pageNumber={countRenderCoin}
                  />
                </div>
              </div>
            </div>
            <div className={styles.pageCounterComponent}>
              <PageCounters
                countOfCoin={
                  search.active ? search.filter.length : coinsInfo.length
                }
                getPageNumber={handelCountRenderCoin}
              />
            </div>
          </>
        ) : null}
      </main>
    </div>
  );
};

export default Home;
