import { Schema, model } from "mongoose";
const assetPriceSchema: Schema = new Schema(
  {
    coinName: {
      type: String,
      required: true,
    },
    symbol: {
      type: String,
      required: true,
    },
    image: {
      type: String,
      required: true,
    },
    price: {
      type: [
        {
          symbol: String,
          priceChange: String,
          priceChangePercent: String,
          weightedAvgPrice: String,
          prevClosePrice: String,
          lastPrice: String,
          lastQty: String,
          bidPrice: String,
          bidQty: String,
          askPrice: String,
          askQty: String,
          openPrice: String,
          highPrice: String,
          lowPrice: String,
          volume: String,
          quoteVolume: String,
          openTime: Number,
          closeTime: Number,
          firstId: Number,
          lastId: Number,
          count: Number,
        },
      ],
      required: true,
    },
    candleStatic: {
      type: {
        m1: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        m3: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        m5: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        m15: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        m30: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        h1: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        h2: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        h4: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        h6: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        h8: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        h12: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        d1: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        d3: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        w1: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
        M1: [
          {
            openTime: Number,
            open: String,
            high: String,
            low: String,
            close: String,
            volume: String,
            closeTime: Number,
            QuoteAssetVolume: String,
            NumberOfTrade: Number,
            TakerBuyBaseAssetVolume: String,
            TakerBuyQuoteAssetVolume: String,
          },
        ],
      },
      required: true,
    },
  },
  { timestamps: true }
);
const assetPrice = model("coins", assetPriceSchema);
module.exports = assetPrice;
